"""Regenerate sql/oracle_schema.sql and sql/oracle_seed.sql from seed_data.py."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from seed_data import SEED_PORTS  # noqa: E402

SQL_DIR = ROOT / "sql"


def main() -> None:
    SQL_DIR.mkdir(exist_ok=True)

    schema = """-- CONCOR demo table for pie-watcher (run once as your Oracle schema user)
-- Example:
--   sqlplus user/password@//host:1521/SERVICE @sql/oracle_schema.sql
-- Or in SQL Developer: open and run this file.

CREATE TABLE port_containers (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    port_terminal VARCHAR2(200)  NOT NULL,
    containers    NUMBER(10)     NOT NULL,
    updated_at    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_port_containers_terminal UNIQUE (port_terminal)
);

COMMENT ON TABLE port_containers IS 'Dummy CONCOR terminal container counts for chart export';
COMMENT ON COLUMN port_containers.port_terminal IS 'Full terminal / ICD / CFS name';
COMMENT ON COLUMN port_containers.containers IS 'Container count (demo)';
"""
    (SQL_DIR / "oracle_schema.sql").write_text(schema.strip() + "\n", encoding="utf-8")

    lines = [
        "-- Seed CONCOR-style terminals (run after oracle_schema.sql)",
        "-- Example:",
        "--   sqlplus user/password@//host:1521/SERVICE @sql/oracle_seed.sql",
        "-- Re-run clears and reloads demo rows.",
        "",
        "DELETE FROM port_containers;",
        "",
    ]
    for name, n in SEED_PORTS:
        esc = name.replace("'", "''")
        lines.append(
            f"INSERT INTO port_containers (port_terminal, containers) "
            f"VALUES ('{esc}', {n});"
        )
    lines += [
        "",
        "COMMIT;",
        "",
        "SELECT COUNT(*) AS row_count FROM port_containers;",
        "SELECT port_terminal, containers FROM port_containers "
        "ORDER BY containers DESC FETCH FIRST 5 ROWS ONLY;",
        "",
    ]
    (SQL_DIR / "oracle_seed.sql").write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {SQL_DIR / 'oracle_schema.sql'}")
    print(f"Wrote {SQL_DIR / 'oracle_seed.sql'} ({len(SEED_PORTS)} inserts)")


if __name__ == "__main__":
    main()
