-- CONCOR demo table for pie-watcher (run once as your Oracle schema user)
-- Example:
--   sqlplus user/password@//host:1521/SERVICE @sql/oracle_schema.sql
-- Or in SQL Developer: open and run this file.

CREATE TABLE port_containers (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    port_terminal VARCHAR2(200)  NOT NULL,
    containers    NUMBER(10)     NOT NULL,
    updated_at    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_port_containers_terminal UNIQUE (port_terminal)
);

COMMENT ON TABLE port_containers IS 'Dummy CONCOR terminal container counts for chart export';
COMMENT ON COLUMN port_containers.port_terminal IS 'Full terminal / ICD / CFS name';
COMMENT ON COLUMN port_containers.containers IS 'Container count (demo)';
